--DECLARE
--    v_rows_deleted VARCHAR2(30);
--    v_empno        HR.employees.employee_id%TYPE := 176;
--BEGIN
--    DELETE FROM hr.job_history
--    WHERE employee_id = v_empno;
--
--    DELETE FROM hr.employees
--    WHERE employee_id = v_empno;
--
--    v_rows_deleted := SQL%ROWCOUNT || ' row(s) deleted.';
--
--    DBMS_OUTPUT.PUT_LINE(v_rows_deleted);
--
--    COMMIT;
--END;
--/
--
--
SELECT * FROM HR.jobs;